### ISSUE TITLE
Captcha was enforced

### ISSUE THREAD

**Issue by innowebka** [KaosDrip/Xensis#1]
how to fix it ?
Captcha was enforced. Please enter a valid authorization code for mail@mail.com

**Comment by KaosDrip** [comment]
Help with the authorization code could be found [here](https://github.com/KaosDrip/Xensis/wiki/Authorization-Code)

**Comment by innowebka** [comment]
> 
> 
> Help with the authorization code could be found [here](https://github.com/KaosDrip/Xensis/wiki/Authorization-Code)

ok i just wanna know before trying is this still working ?

**Comment by innowebka** [comment]
pasted the code and its still  not working

{ "code":"00000000000000"} in auths.json

**Comment by ravenBotDev** [comment]
Open up startBot then paste it there

**Comment by Aspect0002** [comment]
Hey, we updated just download again.
