### ISSUE TITLE
[No address associated with hostname]

### ISSUE THREAD

**Issue by mikekooiman** [KaosDrip/Xensis#14]
Command raised an exception: ClientConnectorError: Cannot connect to host benbot.app:443 ssl:default [No address associated with hostname]

**Comment by Aspect2222** [comment]
This issue has been already fixed, please download latest version. 
Also i am sorry to say, but you only can use IDs at the moment.
Here is a list: https://docs.google.com/spreadsheets/d/1gVDgnzNyMCafIWa-dBO3mgNUHmHzgA9O5sWbfQy2Yfg/edit

**Comment by mikekooiman** [comment]
:)

**Comment by Aspect2222** [comment]
I will continue to work on an update in my free time, if i finally fixed everything i will announce it here.
