### ISSUE TITLE
Empty lobby

### ISSUE THREAD

**Issue by cynorix** [KaosDrip/Xensis#20]
Whenever I join my bot after the latest update, it only shows an empty lobby, my character's not there, the bot's not there, just an empty lobby

how to replicate
1. start the bot
2. join the bot like normal

what I've tried
Restarting the bot
using fortnite_update.py
promoting myself
changing skins on the bot
making the bot emote
!unhide command, bot was promoted
using most of the bot's commands, inlcuding !invisible

result
nothing changed, still no bot or me in the lobby whenever i join

Workaround
inviting the bot in your lobby instead of joining the bot's

Something kind of funny I noticed is that if you join the bot, make it leave and re-invite it, it shows up in your spot, since you're not there

**Comment by Aspect2222** [comment]
Hello, this issue is from the library we use FortnitePY I have asked the developer to fix it, he is working on a fix and it should be updated within 1-3days, I will let you know then.

**Comment by stephengust** [comment]
Any update? I am also getting empty lobbies. Thanks

**Comment by stephengust** [comment]
I was able to find a temporary fix until the devs of FortnitePy update it. 

By changing [these lines](https://github.com/Terbau/fortnitepy/pull/187/commits/7d9f1b33547189915faf4457093db4edb734f62e) in the `party.py` file located inside of `%appdata%\Python\Python39\site-packages\fortnitepy` you can see players in the lobby. 

![image](https://user-images.githubusercontent.com/72709046/224608541-4d877b95-404f-4883-9a90-6101d3f6c124.png)

Here is my updated `party.py` file incase you just want to copy it (It doesn't let me upload Python files so it is a txt that you can copy into `party.py`): 
[party_FortnitePyFix.txt](https://github.com/KaosDrip/Xensis/files/10953568/party_FortnitePyFix.txt)

**Note: Do not update/reinstall FortnitePy (until an official fix is implemented) or it will overwrite this fix .**

If you can't find the `party.py` file or the folder containing it, it probably just means that your python packages are installed somewhere else. One thing you could try is just going to `%appdata%\Python` and finding your package folder from there. If your python version is different, the path will have a number other than 39 in it.

**Comment by Aspect2222** [comment]
> I was able to find a temporary fix until the devs of FortnitePy update it.
> 
> By changing [these lines](https://github.com/Terbau/fortnitepy/pull/187/commits/7d9f1b33547189915faf4457093db4edb734f62e) in the `party.py` file located inside of `%appdata%\Python\Python39\site-packages\fortnitepy` you can see players in the lobby.
> 
> ![image](https://user-images.githubusercontent.com/72709046/224608541-4d877b95-404f-4883-9a90-6101d3f6c124.png)
> 
> Here is my updated `party.py` file incase you just want to copy it (It doesn't let me upload Python files so it is a txt that you can copy into `party.py`): [party_FortnitePyFix.txt](https://github.com/KaosDrip/Xensis/files/10953568/party_FortnitePyFix.txt)
> 
> **Note: Do not update/reinstall FortnitePy (until an official fix is implemented) or it will overwrite this fix .**
> 
> If you can't find the `party.py` file or the folder containing it, it probably just means that your python packages are installed somewhere else. One thing you could try is just going to `%appdata%\Python` and finding your package folder from there. If your python version is different, the path will have a number other than 39 in it.

Thank you, I will look into it and release a fix once I am back from work.
