### ISSUE TITLE
I cant start a match

### ISSUE THREAD

**Issue by GabrielNX** [KaosDrip/Xensis#21]
I get Player.Party Connect_timeout.201

**Comment by Aspect2222** [comment]
You can not play with a bot, as fornitepy and the game does not allow it.
Xensis is a lobby bot not a game bot.

**Comment by GabrielNX** [comment]
How do I make it a lobby bot? It doesn't make sense, it's supposed to be a lobby bot, I add it, it enters, I start the game and I enter a bot-only lobby right?
