### ISSUE TITLE
how to replace credit to terbau

### ISSUE THREAD

**Issue by teenari** [KaosDrip/Xensis#4]
hi :) i was trying to join my bot but it said that stuff it is supposed to say credot to teenari since me create the bot thanks also why you copy my bot before i post it on this

**Comment by KaosDrip** [comment]
? What?

**Comment by teenari** [comment]
> ? What?

how can i replace KaosDrip with teenari yes thanks

**Comment by KaosDrip** [comment]
Replace KaosDrip to teenari where

**Comment by XtremeFN** [comment]
i think when you first open up cmd and it says kaosDrip that's what hes trying to say

**Comment by ghost** [comment]
@teenari ^^^^^^^

**Comment by oofsamy** [comment]
You didnt make the bot, you can easily change the code, what is this.
